GET http://localhost:3000/bbs/board/66a2ddb47fc1ca892ea8ba2a

###

GET http://bluenote-server.onrender.com/bbs/board

###

POST https://bluenote-server.onrender.com/bbs/board
Content-Type: application/json

{
  "subCategory": "일반",
  "writer": "운영자",
  "title": "자유게시판 POST 테스트 35",
  "content": "자유게시판 POST 테스트 35 입니다."
}

###

GET http://localhost:3000/bbs/board/6699ed04d5b61160c5755cc8/comment

###

POST http://localhost:3000/bbs/board/6699ed04d5b61160c5755cc8/comment
Content-Type: application/json

{
  "writer": "테스트",
  "content": "자유게시판 POST 테스트 35 입니다."
}

###

 https://bluenote-server.onrender.com/bbs/board/66a2ddb47fc1ca892ea8ba2a

###

GET https://bluenote-server.onrender.com/bbs/board/6699e30477fa34adc76c731b/comment

###

PATCH https://bluenote-server.onrender.com/bbs/board/6699e30477fa34adc76c731b/comment/669b2a9c75a4a6028fc461ef
Content-Type: application/json

{
  "content": "자유게시판 댓글 수정 테스트"
}