GET https://bluenote-server.onrender.com/bbs/board

###

POST https://bluenote-server.onrender.com/bbs/board
Content-Type: application/json

{
  "subCategory": "일반",
  "writer": "운영자",
  "title": "자유게시판 POST 테스트 15",
  "content": "자유게시판 POST 테스트 15 입니다."
}

###

GET https://bluenote-server.onrender.com/bbs/board/6699e30477fa34adc76c731b

###

DELETE https://bluenote-server.onrender.com/bbs/board/66991430d824011666474c2f